// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ResponseFood;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class item extends Table {
  public static item getRootAsitem(ByteBuffer _bb) { return getRootAsitem(_bb, new item()); }
  public static item getRootAsitem(ByteBuffer _bb, item obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public item __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float price() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createitem(FlatBufferBuilder builder,
      int nameOffset,
      float price) {
    builder.startTable(2);
    item.addPrice(builder, price);
    item.addName(builder, nameOffset);
    return item.enditem(builder);
  }

  public static void startitem(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addPrice(FlatBufferBuilder builder, float price) { builder.addFloat(1, price, 0.0f); }
  public static int enditem(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

