// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ResponseFood;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponseFoodMsg extends Table {
  public static ResponseFoodMsg getRootAsResponseFoodMsg(ByteBuffer _bb) { return getRootAsResponseFoodMsg(_bb, new ResponseFoodMsg()); }
  public static ResponseFoodMsg getRootAsResponseFoodMsg(ByteBuffer _bb, ResponseFoodMsg obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ResponseFoodMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Restaurant resList(int j) { return resList(new Restaurant(), j); }
  public Restaurant resList(Restaurant obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int resListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public String cuisine() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cuisineAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer cuisineInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createResponseFoodMsg(FlatBufferBuilder builder,
      int res_listOffset,
      int cuisineOffset) {
    builder.startTable(2);
    ResponseFoodMsg.addCuisine(builder, cuisineOffset);
    ResponseFoodMsg.addResList(builder, res_listOffset);
    return ResponseFoodMsg.endResponseFoodMsg(builder);
  }

  public static void startResponseFoodMsg(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addResList(FlatBufferBuilder builder, int resListOffset) { builder.addOffset(0, resListOffset, 0); }
  public static int createResListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startResListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCuisine(FlatBufferBuilder builder, int cuisineOffset) { builder.addOffset(1, cuisineOffset, 0); }
  public static int endResponseFoodMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishResponseFoodMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedResponseFoodMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

