// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ResponseCoupon;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class coupon extends Table {
  public static coupon getRootAscoupon(ByteBuffer _bb) { return getRootAscoupon(_bb, new coupon()); }
  public static coupon getRootAscoupon(ByteBuffer _bb, coupon obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public coupon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String couponCode() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer couponCodeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer couponCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String couponPercentage() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer couponPercentageAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer couponPercentageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createcoupon(FlatBufferBuilder builder,
      int coupon_codeOffset,
      int coupon_percentageOffset) {
    builder.startTable(2);
    coupon.addCouponPercentage(builder, coupon_percentageOffset);
    coupon.addCouponCode(builder, coupon_codeOffset);
    return coupon.endcoupon(builder);
  }

  public static void startcoupon(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addCouponCode(FlatBufferBuilder builder, int couponCodeOffset) { builder.addOffset(0, couponCodeOffset, 0); }
  public static void addCouponPercentage(FlatBufferBuilder builder, int couponPercentageOffset) { builder.addOffset(1, couponPercentageOffset, 0); }
  public static int endcoupon(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

