// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ServerProxy;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ProxyMsg extends Table {
  public static ProxyMsg getRootAsProxyMsg(ByteBuffer _bb) { return getRootAsProxyMsg(_bb, new ProxyMsg()); }
  public static ProxyMsg getRootAsProxyMsg(ByteBuffer _bb, ProxyMsg obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ProxyMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Header header() { return header(new Header()); }
  public Header header(Header obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte payloadType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table payload(Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o) : null; }

  public static int createProxyMsg(FlatBufferBuilder builder,
      int headerOffset,
      byte payload_type,
      int payloadOffset) {
    builder.startTable(3);
    ProxyMsg.addPayload(builder, payloadOffset);
    ProxyMsg.addHeader(builder, headerOffset);
    ProxyMsg.addPayloadType(builder, payload_type);
    return ProxyMsg.endProxyMsg(builder);
  }

  public static void startProxyMsg(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(0, headerOffset, 0); }
  public static void addPayloadType(FlatBufferBuilder builder, byte payloadType) { builder.addByte(1, payloadType, 0); }
  public static void addPayload(FlatBufferBuilder builder, int payloadOffset) { builder.addOffset(2, payloadOffset, 0); }
  public static int endProxyMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishProxyMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedProxyMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

