// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ResponseCoupon;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponseCouponMsg extends Table {
  public static ResponseCouponMsg getRootAsResponseCouponMsg(ByteBuffer _bb) { return getRootAsResponseCouponMsg(_bb, new ResponseCouponMsg()); }
  public static ResponseCouponMsg getRootAsResponseCouponMsg(ByteBuffer _bb, ResponseCouponMsg obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ResponseCouponMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String couponForApp() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer couponForAppAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer couponForAppInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String couponFrom() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer couponFromAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer couponFromInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public coupon couponList(int j) { return couponList(new coupon(), j); }
  public coupon couponList(coupon obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int couponListLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createResponseCouponMsg(FlatBufferBuilder builder,
      int coupon_for_appOffset,
      int coupon_fromOffset,
      int coupon_listOffset) {
    builder.startTable(3);
    ResponseCouponMsg.addCouponList(builder, coupon_listOffset);
    ResponseCouponMsg.addCouponFrom(builder, coupon_fromOffset);
    ResponseCouponMsg.addCouponForApp(builder, coupon_for_appOffset);
    return ResponseCouponMsg.endResponseCouponMsg(builder);
  }

  public static void startResponseCouponMsg(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCouponForApp(FlatBufferBuilder builder, int couponForAppOffset) { builder.addOffset(0, couponForAppOffset, 0); }
  public static void addCouponFrom(FlatBufferBuilder builder, int couponFromOffset) { builder.addOffset(1, couponFromOffset, 0); }
  public static void addCouponList(FlatBufferBuilder builder, int couponListOffset) { builder.addOffset(2, couponListOffset, 0); }
  public static int createCouponListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCouponListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endResponseCouponMsg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishResponseCouponMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedResponseCouponMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

