// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ResponseFood;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Restaurant extends Table {
  public static Restaurant getRootAsRestaurant(ByteBuffer _bb) { return getRootAsRestaurant(_bb, new Restaurant()); }
  public static Restaurant getRootAsRestaurant(ByteBuffer _bb, Restaurant obj) { Constants.FLATBUFFERS_1_11_1(); _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public Restaurant __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String resName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer resNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String resRating() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resRatingAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer resRatingInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String resDistance() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resDistanceAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer resDistanceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public app appList(int j) { return appList(new app(), j); }
  public app appList(app obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int appListLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }

  public static int createRestaurant(FlatBufferBuilder builder,
      int res_nameOffset,
      int res_ratingOffset,
      int res_distanceOffset,
      int app_listOffset) {
    builder.startTable(4);
    Restaurant.addAppList(builder, app_listOffset);
    Restaurant.addResDistance(builder, res_distanceOffset);
    Restaurant.addResRating(builder, res_ratingOffset);
    Restaurant.addResName(builder, res_nameOffset);
    return Restaurant.endRestaurant(builder);
  }

  public static void startRestaurant(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addResName(FlatBufferBuilder builder, int resNameOffset) { builder.addOffset(0, resNameOffset, 0); }
  public static void addResRating(FlatBufferBuilder builder, int resRatingOffset) { builder.addOffset(1, resRatingOffset, 0); }
  public static void addResDistance(FlatBufferBuilder builder, int resDistanceOffset) { builder.addOffset(2, resDistanceOffset, 0); }
  public static void addAppList(FlatBufferBuilder builder, int appListOffset) { builder.addOffset(3, appListOffset, 0); }
  public static int createAppListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAppListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRestaurant(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
}

