// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ServerProxy;

public final class AUTH_STATUS {
  private AUTH_STATUS() { }
  public static final int UNKNOWN = 0;
  public static final int SUCCESS = 1;
  public static final int FAILURE = 2;

  public static final String[] names = { "UNKNOWN", "SUCCESS", "FAILURE", };

  public static String name(int e) { return names[e]; }
}

