// automatically generated by the FlatBuffers compiler, do not modify

package com.example.butlerkamaster.FlatbufferDefs.ServerProxy;

public final class Payload {
  private Payload() { }
  public static final byte NONE = 0;
  public static final byte AuthReqMsg = 1;
  public static final byte AuthRespMsg = 2;
  public static final byte ResponseFood_ResponseFoodMsg = 3;
  public static final byte ResponseCoupon_ResponseCouponMsg = 4;

  public static final String[] names = { "NONE", "AuthReqMsg", "AuthRespMsg", "ResponseFood_ResponseFoodMsg", "ResponseCoupon_ResponseCouponMsg", };

  public static String name(int e) { return names[e]; }
}

